#!/usr/bin/env bash

set -eou pipefail

CATCH2_VERSION=${CATCH2_VERSION:-"3.3.2"}

wget -q https://github.com/catchorg/Catch2/archive/refs/tags/v$CATCH2_VERSION.zip -O catch2.zip
unzip -o catch2.zip && rm catch2.zip

pushd Catch2-$CATCH2_VERSION
cmake -B cmake-build-install -H. -DBUILD_TESTING=OFF
sudo cmake --build cmake-build-install --target install
popd
